name: Sifre Guncelleyici

on:
  workflow_dispatch: # Manuel çalıştırma butonu
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        # Cloudscraper ve gerekli araçları buraya ekledik
        run: pip install cloudscraper

      - name: Kodu Calistir
        run: python main.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Dosyaları ekle
          git add liste.m3u kanallar.txt
          
          # Değişiklik varsa kaydet, yoksa hata vermeden geç
          git commit -m "Liste Guncellendi: $(date +'%d-%m-%Y %H:%M')" || echo "Degisiklik yok"
          
          git push
