name: Sifre Guncelleyici

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik çalışır
  workflow_dispatch:      # İstediğinde manuel başlatman için

permissions:
  contents: write         # Dosyaları yazmak ve kaydetmek için gerekli izin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Kimlik bilgilerini sakla

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Kur
        run: pip install requests beautifulsoup4

      - name: Kodu Çalıştır
        run: python main.py

      - name: Değişiklikleri Kontrol Et ve Yükle
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sifre.txt liste.m3u || echo "Eklenecek dosya bulunamadı"
          git commit -m "Güncel Şifre: $(date +'%d-%m-%Y %H:%M')" || echo "Değişiklik yok, commit yapılmadı"
          git push origin main
