name: Sifre Guncelleyici

on:
  workflow_dispatch: # Manuel çalıştırma butonu için

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutupahaneyi Kur
        run: pip install cloudscraper

      - name: Kodu Calistir
        run: python main.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add liste.m3u sifre.txt || echo "Dosya yok"
          git commit -m "Liste Guncellendi" || echo "Degisiklik yok"
          git push
