name: Kanal Listesi Guncelleyici

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    # Yazma izni olmayan bir Action asla dosya kaydedemez
    permissions:
      contents: write

    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Kendi anahtarını kullanmasını sağla

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Kütüphaneleri Kur
      run: pip install cloudscraper

    - name: Guncelle
      run: python main.py

    - name: GitHub'a Zorla Gönder
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add --all
        # Eğer kanallar.m3u oluşmuşsa commit yap
        if git diff --staged --quiet; then
          echo "Değişiklik yok."
        else
          git commit -m "Liste guncellendi: $(date)"
          git push origin main
        fi
