name: Kanal Listesi Guncelleyici

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    # GitHub'a yazma izni verdiğimizi burada kesinleştiriyoruz
    permissions:
      contents: write

    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3
      with:
        persist-credentials: true # Token kullanımını aktif eder

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gerekli Kütüphaneleri Kur
      run: pip install cloudscraper

    - name: Guncelleme Kodunu Calistir
      run: python main.py

    - name: Degisiklikleri GitHub'a Yukle
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Sadece playlist klasörünü ve içindeki m3u8 dosyalarını ekle
        git add playlist/*.m3u8 || echo "Eklenecek yeni dosya bulunamadı"
        
        # Değişiklik varsa kaydet ve gönder
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Otomatik Kanal Güncelleme: $(date)"
          git push
        else
          echo "Herhangi bir değişiklik yok, push yapılmadı."
        fi
