name: Sifre Guncelleyici

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch: # İstediğinde elle başlatman için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v2

      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Kur
        run: pip install requests beautifulsoup4

      - name: Kodu Çalıştır
        run: python Main.py

      - name: Değişiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Şifre güncellendi" || exit 0
          git push
