name: Kanal Listesi Guncelleyici

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # BU SATIR ÇOK ÖNEMLİ

    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Tüm geçmişi çekmesini sağlar

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Kütüphaneleri Kur
      run: pip install cloudscraper

    - name: Guncelle
      run: python main.py

    - name: GitHub'a Gönder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add playlist/*.m3u8 || echo "Dosya bulunamadı"
        git commit -m "Otomatik Güncelleme: $(date)" || echo "Değişiklik yok"
        git push
