name: Sifre Guncelleyici

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch:      # İstediğinde elle başlatman için

permissions:
  contents: write         # Dosyaları kaydedip push yapabilmesi için şart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutupahaneleri Kur
        run: pip install requests beautifulsoup4

      - name: Kodu Calistir
        run: python main.py

      - name: Degisiklikleri Kaydet ve Pushla
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sifre.txt link.txt || echo "Dosyalar bulunamadı"
          git commit -m "Sifre Guncellendi: $(date)" || echo "Degisiklik yok"
          git push
