name: Sifre Guncelleyici

on:
  workflow_dispatch: # Telefondan butona basıp çalıştırmak için
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik çalışma

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kodu Calistir
        run: python main.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Tüm m3u ve txt dosyalarını Git'e tanıtıyoruz
          git add liste.m3u kanallar.txt
          
          # Değişiklik varsa commit yap, yoksa hata vermeden geç
          git commit -m "Otomatik Sifre Guncellendi: $(date +'%Y-%m-%d %H:%M')" || echo "Degisiklik yok"
          
          git push
