name: Kanal Listesi Guncelleyici

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gerekli Kütüphaneleri Kur
      run: |
        pip install cloudscraper

    - name: Guncelleme Kodunu Calistir
      run: |
        python main.py

    - name: Degisiklikleri GitHub'a Yukle
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Hata veren playlist/ yerine '.' kullanarak her şeyi kapsama alıyoruz
        git add .
        # Değişiklik kontrolü ve yükleme
        git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Liste Guncelleme" && git push)
